### ISSUE TITLE
`connect()` can fulfill without ever having connected successfully

### ISSUE THREAD

**Issue by spencerwilson** [originlabs/graphql-postgres-subscriptions#2]
My application startup looks roughly like
```js
  console.log('Initializing pubSub...');
  await pubSubInstance.connect();
  console.log('Initialized!');
  await startServer();
```

I was surprised to find that when Postgres was offline, my application logs looked like this:
```
Initializing pubSub...
  pg-listen:connection Creating PostgreSQL client for notification streaming +0ms
calling connect
Initialized!
  pg-listen:connection DB Client connection ended +18ms
  pg-listen:connection Reconnecting to PostgreSQL for notification streaming +2ms
  pg-listen:connection PostgreSQL reconnection attempt #1... +0ms
  pg-listen:connection PostgreSQL reconnection attempt failed: Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
} +1ms
🚀  Server ready at http://localhost:4000/
  pg-listen:connection PostgreSQL reconnection attempt #2... +508ms
  pg-listen:connection PostgreSQL reconnection attempt failed: Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
} +2ms
  pg-listen:connection PostgreSQL reconnection attempt #3... +506ms
  pg-listen:connection PostgreSQL reconnection attempt failed: Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
} +2ms
  pg-listen:connection PostgreSQL reconnection attempt #4... +505ms
  pg-listen:connection PostgreSQL reconnection attempt failed: Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
} +2ms
  pg-listen:connection PostgreSQL reconnection attempt #5... +505ms
  pg-listen:connection PostgreSQL reconnection attempt failed: Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
} +2ms
  pg-listen:connection PostgreSQL reconnection attempt #6... +502ms
  pg-listen:connection PostgreSQL reconnection attempt failed: Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
} +1ms
  pg-listen:connection Error: Re-initializing the PostgreSQL notification client after connection loss failed: Stopping PostgreSQL reconnection attempts after 3000ms timeout has been reached.
  pg-listen:connection     at /Users/ssw/code/api/node_modules/pg-listen/dist/index.js:108:47
  pg-listen:connection     at step (/Users/ssw/code/api/node_modules/pg-listen/dist/index.js:43:23)
  pg-listen:connection     at Object.next (/Users/ssw/code/api/node_modules/pg-listen/dist/index.js:24:53)
  pg-listen:connection     at step (/Users/ssw/code/api/node_modules/pg-listen/dist/index.js:28:139)
  pg-listen:connection     at Object.next (/Users/ssw/code/api/node_modules/pg-listen/dist/index.js:24:53)
  pg-listen:connection     at fulfilled (/Users/ssw/code/api/node_modules/pg-listen/dist/index.js:15:58) +502ms
```

Is it intended that `connect` can fulfill even when the underlying `pgListen` never connected to the database? It'd be more intuitive (to me) for `connect` to fulfill if and only if it successfully connects (after some number of retries).

A stopgap improvement may be to document what the correct way to await initial connection + listener establishment is. I might do something like
```js
await pubSub.connect();
// Then wait up to 3000 ms (or so) for `pubSub.connected` to become true.
// If it never does, abort.
``` 
since the `connected` boolean seems to be the only way to deduce that the listeners are established.

**Comment by Jonahss** [comment]
Mmm yes I agree, I can't think of a reason why we shouldn't wait for the connection before resolving the promise returned by `connect()`.

We could implement it by adding our own listener for the `connected` event.

If we go past the timeout, is a different error thrown by the underlying library? If so, we can just bubble it up. If not, we can capture the timeout option passed in and set our own timeout for the promise returned by `connect`.

Is this something you'd be interested in submitting a PR for?

**Comment by spencerwilson** [comment]
Potentially! I know GitHub well but have never contributed to anything open source. We'll see how it goes.

To start, I tried running tests. Both natively with Node 16 via
```sh
DATABASE_URL=postgres://postgres:@localhost:5432/postgres PGHOST=localhost PGDATABASE=postgres DEBUG=pg-listen:* PGUSER=postgres npx -n --unhandled-rejections=warn jest
```
and using the documented Docker instructions, I'm getting three test failures:
<details>
  <summary>summary jest output</summary>

```
 FAIL  ./postgres-pubsub.test.js (15.309 s)
  PostgresPubSub
    ✓ PostgresPubSub can subscribe when instantiated without a client (17 ms)
    ✓ PostgresPubSub can subscribe and is called when events happen (5 ms)
    ✓ PostgresPubSub can subscribe when instantiated with connection options but without a client (8 ms)
    ✓ PostgresPubSub can unsubscribe (6 ms)
    ✓ Should emit error when payload exceeds Postgres 8000 character limit (8 ms)
    ✓ AsyncIterator should expose valid asyncIterator for a specific event
    ✕ AsyncIterator should trigger event on asyncIterator when published (5008 ms)
    ✓ AsyncIterator should not trigger event on asyncIterator when publishing other event (13 ms)
    ✕ AsyncIterator should register to multiple events (5008 ms)
    ✕ AsyncIterator transforms messages using commonMessageHandler (5010 ms)
    ✓ PostgresPubSub transforms messages using commonMessageHandler (18 ms)
    ✓ AsyncIterator should not trigger event on asyncIterator already returned (13 ms)

  ● PostgresPubSub › AsyncIterator should trigger event on asyncIterator when published

    : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:

      84 |   });
      85 |
    > 86 |   test("AsyncIterator should trigger event on asyncIterator when published", async (done) => {
         |   ^
      87 |     const eventName = "test";
      88 |     const ps = new PostgresPubSub({ topics: [eventName]});
      89 |     await ps.connect()

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (postgres-pubsub.test.js:86:3)
      at Object.<anonymous> (postgres-pubsub.test.js:6:1)

  ● PostgresPubSub › AsyncIterator should register to multiple events

    : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:

      113 |   });
      114 |
    > 115 |   test("AsyncIterator should register to multiple events", async (done) => {
          |   ^
      116 |     const eventName = "test2";
      117 |     const ps = new PostgresPubSub({ topics: ['test', 'test2']});
      118 |     await ps.connect();

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (postgres-pubsub.test.js:115:3)
      at Object.<anonymous> (postgres-pubsub.test.js:6:1)

  ● PostgresPubSub › AsyncIterator transforms messages using commonMessageHandler

    : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:

      128 |   });
      129 |
    > 130 |   test("AsyncIterator transforms messages using commonMessageHandler", async (done) => {
          |   ^
      131 |     const eventName = "test";
      132 |     const commonMessageHandler = message => ({ transformed: message });
      133 |     const ps = new PostgresPubSub({ commonMessageHandler, topics: [eventName] });

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (postgres-pubsub.test.js:130:3)
      at Object.<anonymous> (postgres-pubsub.test.js:6:1)

Test Suites: 1 failed, 1 total
Tests:       3 failed, 9 passed, 12 total
Snapshots:   0 total
Time:        15.561 s, estimated 16 s
```
</details>

From a glance it seems that these failures are because of this very issue. It seems the `publish` calls made in all three failing tests are returning early via this branch: https://github.com/originlabs/graphql-postgres-subscriptions/blob/86e56c3a33cfadc128138505a3596e38524be607/postgres-pubsub.js#L52-L55, and so failing to spur the expected activity on the asyncIterators.

This raises a couple questions:

1. I thought this issue was a feature request, but might it be a regression? It seems tests might depend on "`connect()` fulfills => `this.connected === true`".
2. Is CI working? I've never used Travis CI as an external contributor on an open source repo so I'm not sure how to tell. Am wondering if tests are passing in that environment.

**Comment by spencerwilson** [comment]
Follow up: All test failures go away when this issue is resolved; see https://github.com/originlabs/graphql-postgres-subscriptions/pull/5.

**Comment by Jonahss** [comment]
Awesome!
The original docker container way of testing from the original repository didn't seem to be working for me, so I was running the tests locally via Jest. Fixing that would be cool.

I also didn't hook up the CI. You could set it up and then we can add the nice badge to the readme. It should be free.
